spring.application.name=shareit-server
spring.main.banner-mode=OFF
server.port=9090

spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always

# TODO Append connection to Postgres DB
spring.datasource.username=dbuser
spring.datasource.password=12345
spring.datasource.url=jdbc:postgresql://localhost:5432/shareit
spring.datasource.driver-class-name=org.postgresql.Driver

